SELECT 
	CAST( fixture__id AS STRING ) as jogo_id,
	fixture__referee as juiz_nome,
	fixture__date as data,
	fixture__status__short as status_id,
	CAST( league__id AS STRING ) as liga_id,
	league__season as temporada,
	league__round as rodada,
	CAST(teams__away__id AS STRING ) AS time_id,
	teams__away__name AS time_nome,
	teams__away__logo AS time_logoUrl,
	teams__away__winner AS time_vitoria,
	goals__away AS gols,
	score__halftime__away AS gols_primeiroTempo,
	score__fulltime__away AS gols_segundoTempo,
	score__extratime__away AS gols_prorrogacao,
	score__penalty__away AS gols_penalti,
	CAST(fixture__venue__id AS STRING) AS estadio_id,
	'Fora' AS casaFora
FROM `soccer_analysis.past_fixtures`